services:
  postgres:
    image: postgres:17
    restart: unless-stopped
    ports: 
      - 5432:5432
    volumes: # Don't remove permanent storage for index database files!
      - "./data/database:/var/lib/postgresql/data/"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_MULTIPLE_DATABASES: ${POSTGRES_MULTIPLE_DATABASES}
    networks:
    - postgres_network

networks:
  postgres_network:
    external: true
