services:
  django_staging:
    container_name: jp_webapp_staging
    build:
      context: .
    restart: always
    ports:
      - 5071:3000
    environment:
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: jp_db_staging
      POSTGRES_PORT: 5432
      POSTGRES_HOST: postgres
      DEV: False
      DEBUG: False
    command: >
      sh -c "python manage.py migrate &&
             python manage.py shell -c 'from django.contrib.auth.models import User; User.objects.filter(username=\"${DJANGO_SUPERUSER_USERNAME}\").exists() or User.objects.create_superuser(\"${DJANGO_SUPERUSER_USERNAME}\", \"${DJANGO_SUPERUSER_EMAIL}\", \"${DJANGO_SUPERUSER_PASSWORD}\")' &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             gunicorn jp_webapp.wsgi:application --bind 0.0.0.0:8000"
    networks:
      - postgres_network
    volumes:
      - ./data:/app/data
  api_staging:
    container_name: jp_api_staging
    image: ghcr.io/gitinference/gitinference/jp-api:stagging
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: jp_db_staging
      POSTGRES_PORT: 5432
      POSTGRES_HOST: postgres
    volumes:
      - ./data:/app/data
    ports:
      - 7001:8000
    networks:
      - postgres_network

networks:
  postgres_network:
    external: true
