name: jp-env
channels:
  - conda-forge
dependencies:
  - pip=23.3.1
  - python=3.12
  - pandas=2.1.4
  - scipy=1.11.4
  - pytest=8.0.0
  - numpy=1.26.4
  - polars=1.2.1
  - plotly=5.18.0
  - pyarrow=17.0.0
  - ipykernel=6.28.0
  - sqlalchemy=2.0.31
  - python-dotenv=1.0.1
  - requests=2.32.3 
  - tqdm=4.66.5 
  - whitenoise=6.7.0
  - sqlmodel=0.0.22
  - ibis-postgres=9.5.0
  - pip:
      - Django==5.0.8
      - psycopg2-binary==2.9.9
