name: Production Docker Image

on:
  push:
    branches: 
      - 'PRODUCTION'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ouslan/jp-webapp:prod

    - name: Push the Docker image
      run: docker push ouslan/jp-webapp:prod
